### ISSUE TITLE
typos in README.md 

### ISSUE THREAD

**Issue by peterjpxie** [NVIDIA/tao_deploy#2]
**Describe the bug**

typos:
```
./README.md:107: dependancies ==> dependencies
```

**Steps/Code to reproduce bug**

review README.md

**Expected behavior**

No typos

**Environment overview (please complete the following information)**

 NA

**Environment details**

NA

**Additional context**

None

**Comment by Arun-George-Zachariah** [comment]
Thanks @peterjpxie for pointing it out. The README has been updated.
